service: recipes-diegog-io

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
package:
  exclude:
    - recipes/.vuepress/**

# define plugins here
plugins:
  - serverless-finch

# client plugin
custom:
  client:
    bucketName: recipes.diegog.io
    distributionFolder: recipes/.vuepress/dist
