name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.20.0
          cache: 'npm'
      - run: npm ci
      - name: get recipes from s3
        run: |
          aws s3 sync s3://"$S3_BUCKET"/recipes ./recipes
      - run: npm run build --if-present
      - name: Upload to S3
        run: |
          aws s3 sync ./recipes/.vuepress/dist s3://"$S3_BUCKET"
      - name: Create Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"